# Pandas + NumPy Data Cleaning — 30 Questions

# 1. Load the CSV using Pandas and display the first 10 rows.

In [1]:
import pandas as pd 
df = pd.read_csv("C:\\Users\\NAYAN\\Downloads\\customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,11-03-2026,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,20-09-2024,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,12-07-2023,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,06-08-2024,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21-07-2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,14-08-2023,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,08-03-2021,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,10-09-2024,Website,normal

# 2. Check the number of rows and columns in the dataset.

In [2]:
rows = df.shape[0]
columns  = df.shape[1]
print("rows:-",rows)
print("columns:-",columns)
# to check the number of rows and columns

rows:- 2000
columns:- 15

# 3. Display all column names and identify which column names contain
# leading/trailing spaces or inconsistent capitalization.

In [3]:
for col in df.columns:
    df.columns = df.columns.str.replace(' ', '_')
    print(repr(col))

'Customer ID'
'Age '
'income_usd'
'credit Score'
'tenure_years'
'monthly_visits'
'satisfaction'
'City'
'customer_segment'
'gender'
'is_active'
'churn_flag'
'signup_date'
'lead_source'
'notes_text'

In [4]:
for i in df.columns:
    print(i)
    if i != i.title():
        df = df.rename(columns = {i:i.title()})
        print(df)

Customer_ID
     Customer_Id         Age_   income_usd credit_Score  tenure_years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      monthly_visits  satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
Age_
income_usd
     Customer_Id         Age_   Income_Usd credit_Score  tenure_years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      monthly_visits  satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
credit_Score
     Customer_Id         Age_   Income_Usd Credit_Score  tenure_years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      monthly_visits  satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
tenure_years
     Customer_Id         Age_   Income_Usd Credit_Score  Tenure_Years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      monthly_visits  satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
monthly_visits
     Customer_Id         Age_   Income_Usd Credit_Score  Tenure_Years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      Monthly_Visits  satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
satisfaction
     Customer_Id         Age_   Income_Usd Credit_Score  Tenure_Years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      Monthly_Visits  Satisfaction       City customer_segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
City
customer_segment
     Customer_Id         Age_   Income_Usd Credit_Score  Tenure_Years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      Monthly_Visits  Satisfaction       City Customer_Segment gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...
1995        no         No  26-02-2024       email            normal
1996         N        Yes  11-08-2024     Website            good
1997       yes         No  27-05-2023         WEB               ???
1998         N        Yes  26-01-2025       Email                ok
1999       yes         No  22-02-2024         ???            good

[2000 rows x 15 columns]
gender
     Customer_Id         Age_   Income_Usd Credit_Score  Tenure_Years  \
0     CUST-01861  45.86741673  28198.41033  660.5629176      5.274076
1     CUST-00354  47.76516428  61312.83129      838 pts      5.632826
2     CUST-01334          NaN  44199.67124  613.1327754           NaN
3     CUST-00906  62.72357805  56259.90961  720.2369862      2.029634
4     CUST-01290          NaN  31238.64196  549.1832523      2.648626
...          ...          ...          ...          ...           ...
1995  CUST-01131  27.26951178  79436.89335  633.9740063     14.007477
1996  CUST-01295  41.09168505  39912.37991  701.7201056      0.673289
1997  CUST-00861  26.21576696  24522.26545  647.7993363      2.026485
1998  CUST-01460   42.3 years  84103.61056      521 pts      7.168156
1999  CUST-01127  59.25609491  53723.87392  576.7390735      9.720663

      Monthly_Visits  Satisfaction       City Customer_Segment Gender  \
0                5.0      3.382150       Pune        consumer     NaN
1                9.0           NaN  Hyderabad         Consumer   Male
2                8.0      4.195157     Mumbai         Consumer      m
3                4.0           NaN    Chennai       Enterprise      m
4                5.0      3.117326     Mumbai       Enterprise   Male
...              ...           ...        ...              ...    ...
1995             NaN      3.556073  Bengaluru         Consumer      M
1996             8.0      2.963094       Pune              SMB      m
1997            12.0      3.079259  Hyderabad             SMB.      F
1998             5.0      3.579652  Hyderabad              SMB    NaN
1999             NaN      1.100520       Pune         Consumer    NaN

     is_active churn_flag signup_date lead_source        notes_text
0          Yes         No  11-03-2026    Referral               NaN
1          NaN         No         NaN     website  follow-up needed
2          Yes         No  20-09-2024       Email               NaN
3            N         No  12-07-2023     Website            normal
4          Yes         No  06-08-2024         NaN               ???
...        ...        ...         ...         ...               ...

In [5]:
# 4. Check the data type of every column using Pandas.
df.dtypes

Customer_Id          object
Age_                 object
Income_Usd           object
Credit_Score         object
Tenure_Years        float64
Monthly_Visits      float64
Satisfaction        float64
City                 object
Customer_Segment     object
Gender               object
Is_Active            object
Churn_Flag           object
Signup_Date          object
Lead_Source          object
Notes_Text           object
dtype: object

In [6]:
# 5. Calculate the number and percentage of missing values in every column.

df.isna().sum() / len(df) * 100

Customer_Id          1.00
Age_                16.55
Income_Usd          22.00
Credit_Score        18.00
Tenure_Years        12.90
Monthly_Visits      14.00
Satisfaction        19.95
City                15.00
Customer_Segment    19.00
Gender              12.00
Is_Active           17.00
Churn_Flag           8.00
Signup_Date         12.00
Lead_Source         21.00
Notes_Text          32.80
dtype: float64

# 6. Find the rows where Customer ID is missing.

In [7]:
df["Customer Id"].isna().sum()

KeyError: 'Customer Id'

In [ ]:
[df[df.columns].isna()]

In [ ]:
# Question 7 — Clean column names

In [ ]:
df.columns.strip(),df.replace(" ","_")

In [ ]:
df.columns = (df.columns.str.strip().str.lower().str.replace(" ", "_"))
print(df)

In [ ]:
# 7. Remove leading/trailing whitespace from all column names and convert them
# to lowercase with underscores.

In [9]:
import pandas as pd
df.columns = (df.columns.str.strip().str.lower().str.replace(" ", "_")
)
df.columns

Index(['customer_id', 'age_', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [ ]:
# 8 Identify duplicate Customer ID values and count how many duplicates exist.

In [19]:
df["customer_id"].duplicated().sum()
df[df["customer_id"].duplicated()]

,customer_id,age_,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,18-03-2022,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,05-12-2021,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,05-09-2021,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,26-12-2022,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,01-07-2021,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,09-07-2024,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,05-07-2023,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,06-06-2026,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,10-10-2024,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,18-07-2024,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,16-09-2023,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,04-12-2023,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,01-01-2023,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,25-08-2024,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,12-10-2023,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,07-07-2024,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03-08-2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,15-02-2022,Social,ok

In [26]:
# 9. Remove duplicate customer records while keeping the first occurrence.
import pandas as pd 

df = df.drop_duplicates(
    subset="customer_id",
    keep="first"
)
df.shape

(1981, 15)

In [27]:
# 10.Find all unique values in the customer_segment column and identify
# inconsistent categories such as Consumer, consumer, consumer , etc.
df["customer_segment"].unique()

array(['consumer ', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [30]:
# 11.Clean the customer_segment column by standardizing capitalization and
# whitespace.
df["customer_segment"] = ( df["customer_segment"].str.strip().str.lower())

df["customer_segment"]

0         consumer
1         consumer
2         consumer
3       enterprise
4       enterprise
           ...
1995      consumer
1996           smb
1997          smb.
1998           smb
1999      consumer
Name: customer_segment, Length: 1981, dtype: object

In [ ]:
# 12.Find all unique values in the gender column and convert them into consistent
# categories such as Male and Female.

In [31]:
df["gender"].unique()

array([nan, 'Male', 'm', 'Female', 'M', 'F', 'f'], dtype=object)

In [ ]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
# No, no, N, 0 become 0.
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and
 #No, no, N, 0 become 0.